# empty lists for teams and their players
def teamListReset():
    Team_0 = []
    Team_1 =[]
    Team_2 =[]
    Team_3 =[]
    Team_4 =[]
    Team_5 =[]
    Team_6 =[]
    Team_7 =[]
    Team_8 =[]
    Team_9 =[]
    Team_10=[]
    Team_11=[]
    Team_12=[]
    Team_13=[]
    Team_14=[]
    Team_15=[]
    Team_16=[]
    Team_17=[]
    Team_18=[]
    Team_19=[]
    Team_20=[]
    Team_21=[]
    Team_22=[]
    Team_23=[]
    Team_24=[]
    Team_25=[]